### ISSUE TITLE
Deployment to Red Hat OpenShift fails due to permission error

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Fast-Neural-Style-Transfer#36]
```
Traceback (most recent call last):
--
  | File "app.py", line 18, in <module>
  | from api import ModelMetadataAPI, ModelPredictAPI
  | File "/workspace/api/__init__.py", line 18, in <module>
  | from .predict import ModelPredictAPI  # noqa
  | File "/workspace/api/predict.py", line 23, in <module>
  | model_wrapper = ModelWrapper()
  | File "/workspace/core/model.py", line 55, in __init__
  | model = torch.load(model_path, map_location=lambda storage, loc: storage)  # cpu only for now ...
  | File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 265, in load
  | f = open(f, 'rb')
  | PermissionError: [Errno 13] Permission denied: 'assets/mosaic.pth'
```

**Comment by MLnick** [comment]
Closed by #37
